<?php defined('BASEPATH') OR exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| A whitelist of functions that Lex can execute to modify variables
|--------------------------------------------------------------------------
*/

$config['allowed_functions']	=	array(
	'character_limiter',
	'count',
	'count_chars',
	'empty',
	'explode',
	'format_date',
	'html_entity_decode',
	'htmlentities',
	'htmlspecialchars',
	'htmlspecialchars_decode',
	'implode',
	'is_array',
	'is_int',
	'is_integer',
	'is_string',
	'isset',
	'ltrim',
	'md5',
	'money_format',
	'nl2br',
	'number_format',
	'preg_match',
	'preg_replace',
	'rtrim',
	'safe_mailto',
	'slugify',
	'sprintf',
	'str_replace',
	'str_word_count',
	'strip_tags',
	'strpos',
	'strtolower',
	'strtoupper',
	'substr',
	'trim',
	'ucfirst',
	'ucwords',
	'word_censor',
	'word_limiter',
	'word_wrap',
        'file_path',
        'form_open',
        'form_open_multipart',
        'form_upload',
        'form_textarea',
        'form_multiselect',
        'form_checkbox',
        'form_reset',
        'form_close',
        'form_input',
        'form_password',
        'form_dropdown',
        'form_radio',
        'form_hidden',
        'form_submit',
        'form_button',
        'form_label',
        'form_fieldset',
        'form_fieldset_close',
        'form_prep',
        'form_error',
        'validation_errors',
        'prepare_intro',
	);

/* End of file parser.php */
